platform :ios do

  desc 'Run Unit Tests'
  lane :unit_test do
    clear_derived_data()
    scan(
      workspace: "Dreams.xcworkspace",
      scheme: 'DreamsTests',
      device: 'iPhone 17',
      clean: false,
      skip_slack: true,
      derived_data_path: "~/Library/Developer/Xcode/DerivedData"
    )
  end

  desc 'Run all available tests'
  lane :test do
    unit_test
  end
end